version: '2'
services:
    research-app:
        image: research
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://research-mysql:3306/research?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8081:8081
    research-mysql:
        extends:
            file: mysql.yml
            service: research-mysql
